services:
  adguard-dns-updater:
    build: .
    container_name: adguard-dns-updater
    environment:
      - ADGUARD_HOST=${ADGUARD_HOST}
      - ADGUARD_PORT=${ADGUARD_PORT:-80}
      - ADGUARD_USE_HTTPS=${ADGUARD_USE_HTTPS:-false}
      - ADGUARD_USERNAME=${ADGUARD_USERNAME}
      - ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
      - HOSTNAMES=${HOSTNAMES}
    restart: unless-stopped
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"